plan_admin:
    resource: "@PlanAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

plan_site:
    resource: "@PlanSiteBundle/Controller/"
    type:     annotation
    prefix:   /

