<?php

namespace Plan\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuicknotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuicknotesRepository extends EntityRepository
{
}
