<?php

namespace Plan\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RelationshipsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationshipsRepository extends EntityRepository
{
}
